feat(promo-code-service): implement API & add docs
danilalisichkin/cab-aggregator-app pull request #61
Opened 2024-12-19 09:26 UTC by danilalisichkin

**This pull request adds representation layer and API documentation of promo code service.**

_Released features:_

1) Representation layer:
- Integrated service layer with representation layer
2) DTO documentation:
- Added documentation for all user requests and server responses
3) Controller documentation:
- Added documentation for all cotrollers and their methods
4) Swagger:
- Added config for Swagger

2024-12-19 18:11 UTC, aleshkey requested changes

2024-12-19 18:11 UTC, aleshkey commented on promo-code-service/src/main/java/com/cabaggregator/promocodeservice/controller/api/PromoStatController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(promoStat);
можно возвращать 201ый статус

2024-12-19 18:11 UTC, aleshkey commented on promo-code-service/src/main/java/com/cabaggregator/promocodeservice/controller/doc/PromoCodeControllerDoc.java
> +            @RequestBody @Valid PromoCodeAddingDto addingDto);
Не уверен, что и в интерфейсе, и в имплементации нужно @Valid. Пробовал без @Valid в одном из мест
?

2024-12-19 18:11 UTC, aleshkey commented on promo-code-service/src/main/resources/openapi/api-docs.yaml
можешь, для общего развития, почитать про OpenAPI generator. Не всем он нравится, но часто встречается

2024-12-23 10:28 UTC, danilalisichkin commented on promo-code-service/src/main/java/com/cabaggregator/promocodeservice/controller/doc/PromoCodeControllerDoc.java
> +            @RequestBody @Valid PromoCodeAddingDto addingDto);
Метод, переопределяющий другой метод, не должен переопределять конфигурацию ограничения параметров:

jakarta.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method X redefines the configuration of Y.

Поэтому в данном случае необходимо, чтобы в методах обоих классов были одни и те же аннотации.

2024-12-23 12:03 UTC, aleshkey approved these changes

2024-12-23 12:05 UTC, merged